Update ligthouse_testing_ci.yml

diff --git a/.github/workflows/ligthouse_testing_ci.yml b/.github/workflows/ligthouse_testing_ci.yml
--- a/.github/workflows/ligthouse_testing_ci.yml
+++ b/.github/workflows/ligthouse_testing_ci.yml
@@ -37,15 +37,19 @@ jobs:
           - name: Start server in the background
             env: 
                 COOKIE_KEY: '1267b291500365c42043e04bc69cf24a31495bd8936fc8d6794283675e288fad755971922d45cf1ca0b438df4fc847f39cb0b2aceb3a45673eff231cddb88dc9'
-            run: cargo leptos watch &
+            run: nohup cargo leptos watch &
 
-          - name: Wait for background process to finish
-            run: wait $!
+          - name: Wait for Leptos build ready
+            run: |   
+              until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:3000/); do
+                sleep 5
+              done
             
-          - name: Install and run Lighthouse
-            run: 
-                npm install -g @lhci/cli@0.13.x
-                lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
+          - name: Install Lighthouse
+            run: npm install -g @lhci/cli@0.13.x
+                
+          - name: run Lighthouse
+            run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
             env: 
                 LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
 
