updated CI

diff --git a/.github/workflows/ligthouse_testing_ci.yml b/.github/workflows/ligthouse_testing_ci.yml
--- a/.github/workflows/ligthouse_testing_ci.yml
+++ b/.github/workflows/ligthouse_testing_ci.yml
@@ -19,29 +19,29 @@ jobs:
                 node-version: 20
           - run: npm install
 
-          - name: Install Lighthouse
-            run: npm install -g @lhci/cli@0.13.x
+          # - name: Install Lighthouse
+          #   run: npm install -g @lhci/cli@0.13.x
 
-          - name: Run Lighthouse
-            run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
-            env: 
-                LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          # - name: Run Lighthouse
+          #   run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
+          #   env: 
+          #       LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
 
           - name: install playwright
             run: npx playwright install    
 
           - name: run playwright
             id: tests
-            run: TESTPARAM=${{secrets.MAIL_PASSWORD}} npx playwright test --project=firefox
+            run: npx playwright test --project=firefox
             continue-on-error: true
 
-          - name: Notify Google Chat on success
-            if: success()
-            uses: 'google-github-actions/send-google-chat-webhook@v0.0.2'
-            with:
-              webhook_url: '${{ secrets.TEST_WEBHOOK_URL }}'
-              # mention: "<users/all>"
-              message: 'Playwright Tests Passed! !!!!!'
+          # - name: Notify Google Chat on success
+          #   if: success()
+          #   uses: 'google-github-actions/send-google-chat-webhook@v0.0.2'
+          #   with:
+          #     webhook_url: '${{ secrets.TEST_WEBHOOK_URL }}'
+          #     # mention: "<users/all>"
+          #     message: 'Playwright Tests Passed! !!!!!'
 
           - name: Notify Google Chat on failure
             if: failure()
