updated ci for lighthouse report in pr comment

diff --git a/.github/workflows/ligthouse_testing_ci.yml b/.github/workflows/ligthouse_testing_ci.yml
--- a/.github/workflows/ligthouse_testing_ci.yml
+++ b/.github/workflows/ligthouse_testing_ci.yml
@@ -17,14 +17,19 @@ jobs:
                 node-version: 20
           - run: npm install
 
+          - uses: actions/checkout@master
+          - name: Lighthouse
+            uses: foo-software/lighthouse-check-action@master
+            with:
+              urls: 'https://www.yral.com'
     
-          - name: Install Lighthouse
-            run: npm install -g @lhci/cli@0.13.x
+          # - name: Install Lighthouse
+          #   run: npm install -g @lhci/cli@0.13.x
 
-          - name: Run Lighthouse
-            run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
-            env: 
-                LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          # - name: Run Lighthouse
+          #   run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
+          #   env: 
+          #       LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
 
           # - name: install playwright
           #   run: npx playwright install    
@@ -41,31 +46,6 @@ jobs:
           #     url: ${{ secrets.TEST_WEBHOOK_URL }}
           #     status: ${{ steps.tests.outcome }}
 
-
-
-          # using outcome as status
-          # - name: Notify Google Chat
-          #   uses: google-github-actions/send-google-chat-webhook@v0.0.2
-          #   with:
-          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
-          #     message: ${{ steps.tests.outcome }}
-
-          # - name: Notify Google Chat on success
-          #   if: success()
-          #   uses: google-github-actions/send-google-chat-webhook@v0.0.2
-          #   with:
-          #     webhook_url: '${{ secrets.TEST_WEBHOOK_URL }}'
-          #     # mention: "<users/all>"
-          #     # message: 'Playwright Tests Passed! !!!!!'
-          #     status: ${{ steps.tests.outcome }}
-
-          # - name: Notify Google Chat on failure
-          #   # if: failure()
-          #   uses: google-github-actions/send-google-chat-webhook@v0.0.2
-          #   with:
-          #     # name: Build
-          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
-          #     status: ${{ steps.tests.outcome }}
 
           - name: Check test result and comment
             uses: peter-evans/create-or-update-comment@v1
