Update ligthouse_testing_ci.yml

diff --git a/.github/workflows/ligthouse_testing_ci.yml b/.github/workflows/ligthouse_testing_ci.yml
--- a/.github/workflows/ligthouse_testing_ci.yml
+++ b/.github/workflows/ligthouse_testing_ci.yml
@@ -33,13 +33,13 @@ jobs:
                 node-version: 20
           - run: npm install
 
-          # - name: Install Lighthouse
-          #   run: npm install -g @lhci/cli@0.13.x
+          - name: Install Lighthouse
+            run: npm install -g @lhci/cli@0.13.x
 
-          # - name: Run Lighthouse
-          #   run: lhci autorun --upload.githubToken="$LHCI_GITHUB_APP_TOKEN" || echo "LHCI failed!"
-          #   env: 
-          #       LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          - name: Run Lighthouse
+            run: lhci autorun --upload.githubToken="$LHCI_GITHUB_APP_TOKEN" || echo "LHCI failed!"
+            env: 
+                LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
 
           - name: install playwright
             run: npx playwright install    
