updated lhci test

diff --git a/.github/workflows/ligthouse_testing_ci.yml b/.github/workflows/ligthouse_testing_ci.yml
--- a/.github/workflows/ligthouse_testing_ci.yml
+++ b/.github/workflows/ligthouse_testing_ci.yml
@@ -17,6 +17,21 @@ jobs:
                 node-version: 20
           - run: npm install
 
+
+          - uses: actions/checkout@master
+          - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
+          - name: Lighthouse
+            uses: foo-software/lighthouse-check-action@master
+            with:
+              outputDirectory: ${{ github.workspace }}/tmp/artifacts
+              gitHubAccessToken: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+              urls: 'https://yral.com/'
+          - name: Upload artifacts
+            uses: actions/upload-artifact@master
+            with:
+              name: Lighthouse reports
+              path: ${{ github.workspace }}/tmp/artifacts
+
           # - uses: actions/checkout@master
           # - run: mkdir /tmp/artifacts
           # - name: Lighthouse
@@ -27,14 +42,14 @@ jobs:
           #     outputDirectory: /tmp/artifacts
           #     urls: 'https://yral.com/'
     
-          - name: Install Lighthouse
-            run: npm install -g @lhci/cli@0.13.x
+          # - name: Install Lighthouse
+          #   run: npm install -g @lhci/cli@0.13.x
 
-          - name: Run Lighthouse
-            id: lhcitests
-            run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
-            env: 
-                LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          # - name: Run Lighthouse
+          #   id: lhcitests
+          #   run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
+          #   env: 
+          #       LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
 
           # - name: install playwright
           #   run: npx playwright install    
@@ -52,15 +67,15 @@ jobs:
           #     status: ${{ steps.tests.outcome }}
 
 
-          - name: Check test result and comment
-            uses: peter-evans/create-or-update-comment@v1
-            with:
-              token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-              issue-number: ${{ github.event.pull_request.number }}
-              body: |
-                ${{ steps.lhcitests.outcome }}
+          # - name: Check test result and comment
+          #   uses: peter-evans/create-or-update-comment@v1
+          #   with:
+          #     token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          #     issue-number: ${{ github.event.pull_request.number }}
+          #     body: |
+          #       ${{ steps.lhcitests.outcome }}
             
-          - run: echo "${{ steps.lhcitests.outcome }}"
+          # - run: echo "${{ steps.lhcitests.outcome }}"
                     
 
           # - name: Trigger a workflow in another repo
